#version: '3.3'
services:
    web:
        image: nginx:latest
        ports:
          - "82:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    app:
        build:
            context: ./php
            dockerfile: Dockerfile
            # File pour créer des images qui sont utilisés pour construire vos containers
            # Image existe déja mais on va la personaliser
        volumes:
            -   ./app:/app
    db:
        image: mysql:8.0
        volumes:
            -   mysqldata:/var/lib/mysql
        ports:
            - "4306:3306"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: docker-php
volumes:
    mysqldata: