#version: '3.3'
services:
    web:
        image: nginx:latest
        ports:
          - "82:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    app:
        build:
            context: ./php
            dockerfile: Dockerfile
            # File pour créer des images qui sont utilisés pour construire vos containers
            # Image existe déja mais on va la personaliser
        volumes:
            -   ./app:/app