# docker-compose -f docker-compose.dev.yaml up --build -d
# docker-compose -f docker-compose.dev.yaml  --env-file .env.local up --build -d (before commit multi composer)
services:
    # nginx
    # docker exec -it docker-php_app_1 bin/bash
    web:
        #image: nginx:latest
        build:
            context: .
            dockerfile: nginx/Dockerfile
        ports:
          - "82:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # php
    # docker exec -it docker-php_app_1 sh
    app:
        build:
            # When building a Docker image,
            # The build context is the directory Docker uses to look for files to copy into the image.
            context: .
            dockerfile: php/Dockerfile
            # File pour créer des images qui sont utilisés pour construire vos containers
            # Image exist aleardy bu we gonna customise
            target: "${BUILD_TARGET:-app}"
        volumes:
            # If I specify just the one location, I am saying protect this location inside the container
            # - /var/www/html/vendor
            - ./app:/var/www/html
            # Si tu veux modifier le fichier sans reconstruire l'image
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        environment:
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
            # XDEBUG_MODE=debug docker-compose -f docker-compose.dev.yaml up --build -d
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            # La directive extra_hosts permet d'ajouter des entrées dans le fichier /etc/hosts du conteneur Docker.
            # Sous Linux, host.docker.internal n’est pas nativement pris en charge par Docker,
            # comme c’est le cas pour Windows et Mac.
            # Donc, cette ligne permet de contourner ce problème en dirigeant
            # host.docker.internal vers l'IP de la passerelle de l’hôte.
            # host-gateway est une fonctionnalité introduite dans Docker 20.10,
            # qui permet de récupérer dynamiquement l'IP de la passerelle Docker
            # (l’interface réseau qui connecte l’hôte à ses conteneurs).
            - host.docker.internal:host-gateway
    # mysql
    db:
        ports:
            - "4306:3306"
        restart: unless-stopped
volumes:
    mysqldata:
# docker-composer up --build ( will look at my docker files and build images for me )