services:
    # nginx
    web:
        image: aminedocker/nginx-php:1.0
        ports:
            - "82:80"
    # php
    app:
        image: aminedocker/php-composer:1.1
        environment:
            MYSQL_HOST: db
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            REDIS_HOST: cache
            REDIS_PORT: ${REDIS_PORT}
    # mysql
    db:
        image: mysql:8.0
        volumes:
            # to stock the data of BDD MySQL in the folder /var/lib/mysql of container.
            # Cela garantit que les données persistent même après que le conteneur est supprimé ou reconstruit.
            -   mysqldata:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
    # redis
    # docker exec -ti docker-php_cache_1 redis-cli
    cache:
        image: redis:latest
volumes:
    mysqldata:
# docker-composer up --build ( will look at my docker files and build images for me )